[project]
name = "4o-ghibli-at-home"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask",
    "flask-cors",
    "python-dotenv",
    "loguru",
    "torch",
    "Pillow",
    "diffusers",
    "dfloat11",
]
